-- MySQL Script generated by MySQL Workbench
-- Fri Jul 21 04:59:02 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema notes
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `notes` ;

-- -----------------------------------------------------
-- Schema notes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `notes` DEFAULT CHARACTER SET utf8 ;
USE `notes` ;

-- -----------------------------------------------------
-- Table `notes`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `notes`.`user` ;

CREATE TABLE IF NOT EXISTS `notes`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `avatar` LONGTEXT NULL,
  `email` VARCHAR(45) NOT NULL,
  `role` ENUM("ROLE_USER", "ROLE_ADMIN") NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notes`.`notes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `notes`.`notes` ;

CREATE TABLE IF NOT EXISTS `notes`.`notes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `text` LONGTEXT NULL,
  `isPublic` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notes`.`user_has_notes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `notes`.`user_has_notes` ;

CREATE TABLE IF NOT EXISTS `notes`.`user_has_notes` (
  `user_id` INT NOT NULL,
  `notes_id` INT NOT NULL,
  `role` ENUM("ROLE_VIEW", "ROLE_EDIT") NOT NULL,
  PRIMARY KEY (`user_id`, `notes_id`),
  CONSTRAINT `fk_user_has_notes_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `notes`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_has_notes_notes1`
    FOREIGN KEY (`notes_id`)
    REFERENCES `notes`.`notes` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_user_has_notes_notes1_idx` ON `notes`.`user_has_notes` (`notes_id` ASC) VISIBLE;

CREATE INDEX `fk_user_has_notes_user_idx` ON `notes`.`user_has_notes` (`user_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
